server:
  port: 8443
  ssl:
    keystore: file:///Users/wonjong/Documents/Study/Projects/Spring in Action/taco-cloud/mykeys.jks
    key-store-password: password
    key-password: password
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/springinactiondb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

taco:
  orders:
    pageSize: 10

logging:
  level:
    tacos: DEBUG