spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/springinactiondb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true